# Generated by Django 5.1.4 on 2025-01-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='festivels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivelname', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('usertype', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='images')),
                ('total_days', models.CharField(max_length=250)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inclusion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantname', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotname', models.CharField(blank=True, max_length=200, null=True)),
                ('placename', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='spots/')),
            ],
        ),
        migrations.CreateModel(
            name='Travelagenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mailid', models.CharField(blank=True, max_length=200, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('idproof', models.CharField(blank=True, max_length=200, null=True)),
                ('licencenumber', models.BigIntegerField(blank=True, null=True)),
                ('loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='modelproduct',
        ),
        migrations.AddField(
            model_name='package_detail',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.places'),
        ),
    ]
