# Generated by Django 5.1.4 on 2025-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_festivels_logintable_package_detail_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
